flowchart TD
  demo_client(Client)
  demo_dns([DNS])
  demo_firewall[Firewall]
  demo_cdn([CDN])
  demo_lb[Load Balancer]
  demo_reverse_proxy[Reverse Proxy]
  demo_apigw[API Gateway]
  demo_service[Service]
  demo_mq[/Message Queue/]
  demo_db_master[(Database)]
  demo_db_slave[(Database)]
  demo_cache{{Cache}}
  demo_storage[(Storage)]
  demo_monitor[Monitor]

  demo_client -->|DNS | sync| demo_dns
  demo_client -->|HTTPS | sync| demo_cdn
  demo_client -->|HTTPS | sync| demo_firewall
  demo_firewall -->|HTTPS | sync| demo_lb
  demo_cdn -->|HTTPS | sync| demo_storage
  demo_lb -->|HTTP | sync| demo_reverse_proxy
  demo_reverse_proxy -->|HTTP | sync| demo_apigw
  demo_apigw -->|HTTP | sync| demo_service
  demo_service -.->|AMQP | async| demo_mq
  demo_service -->|DATABASE | sync| demo_db_master
  demo_service -->|DATABASE | sync| demo_db_slave
  demo_service -->|RESP | sync| demo_cache
  demo_service -.->|HTTP | async| demo_monitor
